services:
  subscriber:
    container_name: subscriber
    build:
      context: ./Subscriber
    image: subscriber:latest
    network_mode: host
    environment:
      - BROKER_HOST=127.0.0.1

  publisher:
    container_name: publisher
    build:
      context: ./Publisher
    image: publisher:latest
    network_mode: host
    environment:
      - ASPNETCORE_URLS=http://+:5000
      - BROKER_HOST=127.0.0.1
      - SUBSCRIBER_HOST=127.0.0.1
