services:
  subscriber:
    container_name: subscriber
    build:
      context: ./Subscriber
    image: subscriber:latest
    ports:
      - "11000:11000/udp"
    networks:
      - udp-net

networks:
  udp-net:
    driver: bridge